(function () {
  "use strict";

  var SETTINGS_KEY = "reader_preferences_v2";
  var BOUND_CONVERSATION_KEY = "bound_conversation_id";
  var BOUND_CONVERSATION_TITLE_KEY = "bound_conversation_title";
  var PAGE_BATCH = 5;
  var state = {
    books: [], book: null, bookmarks: [], page: 1, view: "library", rangeEnd: 0, loadingMore: false,
    boundConversationId: "", boundConversationTitle: "", selectedQuote: "", activeNote: null,
    settings: { theme: "paper", fontSize: 21, brightness: 0 }
  };
  var el = {};
  var toastTimer;
  var scrollTimer;
  var progressTimer;
  var themes = ["paper", "night", "sepia", "blush"];

  function id(name) { return document.getElementById(name); }
  function esc(value) { return String(value === null || value === undefined ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
  function text(value) { return String(value === null || value === undefined ? "" : value).replace(/^\s+|\s+$/g, ""); }
  function toast(message) { el.toast.textContent = message; el.toast.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(function () { el.toast.classList.remove("show"); }, 2800); }
  function bridge() {
    return new Promise(function (resolve, reject) {
      var count = 0;
      var timer = setInterval(function () {
        count++;
        if (window.Bridge) { clearInterval(timer); resolve(window.Bridge); }
        else if (count > 100) { clearInterval(timer); reject(new Error("插件桥接失败")); }
      }, 50);
    });
  }
  function parse(value) { if (value === null || typeof value === "object") return value; try { var result = JSON.parse(value); return typeof result === "string" ? JSON.parse(result) : result; } catch (error) { return value; } }
  function tool(name, params) { return bridge().then(function (instance) { return instance.callTool(name, JSON.stringify(params || {})); }).then(function (result) { result = parse(result); if (result && result.result) result = parse(result.result); if (Array.isArray(result)) result = parse(result[0]); return result || {}; }); }
  function getData(key) { return bridge().then(function (instance) { return instance.getData ? instance.getData(key) : instance.dataStoreGet(key); }); }
  function setData(key, value) { return bridge().then(function (instance) { return instance.setData ? instance.setData(key, value) : instance.dataStoreSet(key, value); }); }
  function getConversations() { return bridge().then(function (instance) { if (!instance.listConversations) throw new Error("Daddy 需要更新到共读窗口版后才能选择聊天窗"); return instance.listConversations(); }).then(parse); }
  function sendConversationMessage(conversationId, content) { return bridge().then(function (instance) { if (!instance.sendConversationMessage) throw new Error("Daddy 需要更新到共读窗口版后才能让指定聊天窗回复"); return instance.sendConversationMessage(conversationId, content); }).then(parse); }
  function percentText(book) { var percent = Number(book.progress_percent || 0); if (percent <= 0) return "未读"; if (percent >= 100) return "已读完"; return "已读 " + percent + "%"; }
  function coverKind(book) { return /\.md$/i.test(String(book.title || "")) ? "- MD -" : "- TXT -"; }
  function sortBooks() { state.books.sort(function (a, b) { return String(a.updated_at || a.added_at) < String(b.updated_at || b.added_at) ? 1 : -1; }); }
  function loadPreferences() { return Promise.all([getData(SETTINGS_KEY), getData(BOUND_CONVERSATION_KEY), getData(BOUND_CONVERSATION_TITLE_KEY)]).then(function (values) { if (values[0]) { var saved = parse(values[0]); if (saved && typeof saved === "object") { Object.keys(state.settings).forEach(function (key) { if (saved[key] !== undefined) state.settings[key] = saved[key]; }); } } state.boundConversationId = text(values[1]); state.boundConversationTitle = text(values[2]); }).catch(function () {}); }
  function savePreferences() { return setData(SETTINGS_KEY, JSON.stringify(state.settings)).catch(function () {}); }
  function load() { return tool("list_books", {}).then(function (result) { state.books = result.books || []; sortBooks(); renderLibrary(); }); }
  function renderLibrary() {
    var bookmarks = state.view === "bookmarks";
    el.library.hidden = bookmarks; el.empty.hidden = bookmarks || state.books.length !== 0; el.bookmarkPanel.hidden = !bookmarks; el.importButton.hidden = bookmarks; el.aiBindingButton.hidden = bookmarks;
    Array.prototype.forEach.call(document.querySelectorAll(".nav-item"), function (button) { button.classList.toggle("is-active", button.getAttribute("data-view") === state.view); });
    renderBinding();
    if (bookmarks) { renderBookmarks(); return; }
    el.library.innerHTML = state.books.map(function (book) { var percent = Math.max(0, Math.min(100, Number(book.progress_percent || 0))); return '<article class="book" data-id="' + esc(book.id) + '"><button class="book-open" data-open aria-label="阅读 ' + esc(book.title) + '"><span class="book-cover" data-kind="' + esc(coverKind(book)) + '"><span class="cover-title">' + esc(book.title) + '</span></span><span class="book-name">' + esc(book.title) + '</span><span class="book-meta">' + esc(percentText(book)) + '</span><span class="mini-progress"><i style="width:' + percent + '%"></i></span></button></article>'; }).join("");
  }
  function renderBinding() { var bound = !!state.boundConversationId; el.aiBindingButton.classList.toggle("is-bound", bound); el.aiBindingTitle.textContent = bound ? state.boundConversationTitle || "已选择的 Daddy" : "选择共读 Daddy"; el.aiBindingCopy.textContent = bound ? "批注会带着这个窗口的记忆回复" : "批注会送进这个聊天窗口"; }
  function renderBookmarks() { tool("list_reading_bookmarks", {}).then(function (result) { var items = result.bookmarks || []; el.bookmarkPanel.innerHTML = !items.length ? '<div class="empty-state"><span>🔖</span><b>还没有书签</b><p>读到想停下来的地方，点阅读页顶部的小书签。</p></div>' : '<h2 class="bookmark-heading">书签</h2>' + items.map(function (item) { return '<button class="bookmark-card" data-bookmark-book="' + esc(item.book_id) + '" data-bookmark-page="' + Number(item.page) + '"><span class="bookmark-page">' + Number(item.page) + '</span><span><b>' + esc(item.label || "第 " + item.page + " 页") + '</b><small>' + esc(item.book_title || "共读书房") + '</small></span></button>'; }).join(""); }).catch(function () { el.bookmarkPanel.innerHTML = '<p class="toc-empty">书签读取失败，稍后再试试。</p>'; }); }
  function splitText(value) { var pages = [], buffer = ""; String(value || "").replace(/\r/g, "").replace(/\n{4,}/g, "\n\n").trim().split(/\n{2,}/).forEach(function (part) { part = text(part); if (!part) return; if (buffer && buffer.length + part.length + 2 > 2200) { pages.push(buffer); buffer = ""; } while (part.length > 2400) { if (buffer) { pages.push(buffer); buffer = ""; } pages.push(part.slice(0, 2200)); part = part.slice(2200); } buffer += (buffer ? "\n\n" : "") + part; }); if (buffer) pages.push(buffer); return pages; }
  function uid() { return Date.now() + "_" + Math.floor(Math.random() * 1000000); }
  function importBook() { bridge().then(function (instance) { return instance.pickFile(); }).then(function (result) { if (!result || result.success === false) { if (result && result.error !== "User cancelled") toast(result.error || "导入失败"); return null; } var title = prompt("书名", String(result.fileName || "未命名").replace(/\.[^.]+$/, "")); if (title === null || !title.trim()) return null; var author = prompt("作者（可以留空）", ""); if (author === null) return null; var pages = splitText(result.content); if (!pages.length) throw new Error("文件里没有可读取的文字"); return { title: title.trim(), author: author.trim(), pages: pages }; }).then(function (source) { if (!source) return null; var bookId = uid(), book = { id: bookId, title: source.title, author: source.author, total_pages: source.pages.length, progress_page: 1, added_at: new Date().toISOString(), updated_at: new Date().toISOString() }, chain = Promise.resolve(); source.pages.forEach(function (pageText, index) { chain = chain.then(function () { return setData("chunk_" + bookId + "_" + (index + 1), pageText); }); }); return chain.then(function () { return setData("book_" + bookId, JSON.stringify(book)); }).then(function () { return setData("current_book", bookId); }).then(function () { return book; }); }).then(function (book) { if (!book) return; toast("《" + book.title + "》已放进我们的书架"); return load(); }).catch(function (error) { toast(error.message || "导入失败"); }); }
  function readPage(page) { return tool("read_book_page", { book_ref: state.book.id, page: page, allow_spoiler: true }).then(function (result) { if (result.success === false) throw new Error(result.error || "读取失败"); return result; }); }
  function fetchRange(from, to) { var jobs = [], page; for (page = from; page <= to; page++) jobs.push(readPage(page)); return Promise.all(jobs); }
  function openBook(book, page) { state.book = book; state.page = Math.max(1, Math.min(Number(page || book.progress_page || 1), Number(book.total_pages))); state.rangeEnd = 0; el.reader.hidden = false; document.body.style.overflow = "hidden"; applySettings(); setReaderControlsVisible(false); loadReadingWindow(state.page, true); }
  function loadReadingWindow(page, resetScroll) { var from = Math.max(1, page - 2), to = Math.min(Number(state.book.total_pages), page + PAGE_BATCH - 1); el.text.innerHTML = '<p class="loading-more">正在打开这一段…</p>'; readPage(page).then(function (first) { return fetchRange(from, to).then(function (pages) { refreshBook(first.book); state.bookmarks = first.bookmarks || []; state.page = page; state.rangeEnd = to; renderPages(pages, false); updateReaderHeader(); if (resetScroll) { requestAnimationFrame(function () { var target = el.text.querySelector('[data-page="' + page + '"]'); if (target) target.scrollIntoView({ block: "start" }); else el.reader.scrollTop = 0; }); } advanceProgress(page); }); }).catch(function (error) { toast(error.message || "读取失败"); }); }
  function appendMorePages() { if (state.loadingMore || !state.book || state.rangeEnd >= state.book.total_pages) return; state.loadingMore = true; el.loadingMore.hidden = false; var from = state.rangeEnd + 1, to = Math.min(Number(state.book.total_pages), state.rangeEnd + PAGE_BATCH); fetchRange(from, to).then(function (pages) { state.rangeEnd = to; renderPages(pages, true); }).catch(function () { toast("下一段没有加载成功，稍后再滑一次试试。"); }).finally(function () { state.loadingMore = false; el.loadingMore.hidden = true; }); }
  function refreshBook(book) { var index = state.books.findIndex(function (item) { return item.id === book.id; }); if (index >= 0) state.books[index] = book; state.book = book; }
  function noteAnswered(note) { return note.status === "answered" || !!note.ai_reply || note.author === "ai"; }
  function highlightText(content, notes) { var html = esc(content); (notes || []).filter(function (note) { return note.quote && note.quote.length > 1; }).sort(function (a, b) { return b.quote.length - a.quote.length; }).forEach(function (note) { var quote = esc(note.quote); var marker = '<mark class="quote-anchor ' + (noteAnswered(note) ? "answered" : "pending") + '" data-note-id="' + esc(note.id) + '">' + quote + '</mark>'; if (html.indexOf(quote) >= 0) html = html.replace(quote, marker); }); return html; }
  function renderPages(pages, append) { var html = pages.map(function (result) { var notes = result.notes || []; var cards = notes.length ? '<div class="page-notes">' + notes.map(function (note) { var answered = noteAnswered(note); var status = answered ? "Daddy 已回复" : "等待 Daddy"; var copy = note.ai_reply || note.content; return '<button class="inline-note" data-note-id="' + esc(note.id) + '"><b>' + (answered ? "Daddy" : "应帆") + ' · ' + status + '</b><small>' + esc(copy) + '</small></button>'; }).join("") + '</div>' : ""; return '<section class="read-page" data-page="' + Number(result.page) + '"><p class="page-label">第 ' + Number(result.page) + ' / ' + Number(result.book.total_pages) + ' 页</p><p class="page-copy">' + highlightText(result.text, notes) + '</p>' + cards + '</section>'; }).join(""); if (append) el.text.insertAdjacentHTML("beforeend", html); else el.text.innerHTML = html; }
  function updateBookmarkButton() { var saved = state.bookmarks.some(function (bookmark) { return Number(bookmark.page) === Number(state.page); }); el.bookmarkButton.classList.toggle("bookmark-on", saved); el.bookmarkButton.classList.toggle("bookmark-off", !saved); el.bookmarkButton.setAttribute("aria-label", saved ? "本页已设置书签" : "本页未设置书签"); el.bookmarkButton.setAttribute("title", saved ? "本页已设置书签" : "本页未设置书签"); }
  function updateReaderHeader() { var total = Number(state.book.total_pages), percent = total <= 1 ? 100 : Math.round((state.page - 1) * 1000 / (total - 1)) / 10; el.bookTitle.textContent = state.book.title; el.pageInfo.textContent = "第 " + state.page + " / " + total + " 页 · " + percent + "%"; el.readingProgress.min = "1"; el.readingProgress.max = String(total); el.readingProgress.value = String(state.page); el.chapterHint.textContent = "上下滑动阅读 · 点击正文中央显示目录和阅读设置"; updateBookmarkButton(); }
  function advanceProgress(page) { if (!state.book || page <= Number(state.book.progress_page || 1)) return; state.book.progress_page = page; clearTimeout(progressTimer); progressTimer = setTimeout(function () { tool("update_reading_progress", { book_ref: state.book.id, page: page }).then(function (result) { if (result.book) refreshBook(result.book); }).catch(function () {}); }, 500); }
  function currentVisiblePage() { var pages = el.text.querySelectorAll(".read-page"), point = window.innerHeight * .42, closest = null, distance = Infinity; Array.prototype.forEach.call(pages, function (item) { var rect = item.getBoundingClientRect(), center = (rect.top + rect.bottom) / 2, d = Math.abs(center - point); if (d < distance) { closest = item; distance = d; } }); return closest ? Number(closest.getAttribute("data-page")) : state.page; }
  function onReaderScroll() { clearTimeout(scrollTimer); scrollTimer = setTimeout(function () { var next = currentVisiblePage(); if (next && next !== state.page) { state.page = next; updateReaderHeader(); advanceProgress(next); } if (el.reader.scrollTop + el.reader.clientHeight > el.reader.scrollHeight - 900) appendMorePages(); }, 80); }
  function setReaderControlsVisible(visible) { el.reader.classList.toggle("controls-hidden", !visible); if (!visible) el.brightnessPopover.hidden = true; }
  function toggleReaderControls() { setReaderControlsVisible(el.reader.classList.contains("controls-hidden")); }
  function applySettings() { el.reader.classList.remove("theme-paper", "theme-night", "theme-sepia", "theme-blush"); el.reader.classList.add("theme-" + state.settings.theme); el.text.style.fontSize = Number(state.settings.fontSize) + "px"; el.dimmer.style.opacity = Math.max(0, Math.min(62, Number(state.settings.brightness))) / 100; el.brightness.value = state.settings.brightness; }
  function changeFont(delta) { state.settings.fontSize = Math.max(15, Math.min(31, Number(state.settings.fontSize) + delta)); applySettings(); savePreferences(); toast("字号 " + state.settings.fontSize + " px"); }
  function cycleTheme() { var index = themes.indexOf(state.settings.theme); state.settings.theme = themes[(index + 1) % themes.length]; applySettings(); savePreferences(); toast(({ paper: "日间", night: "夜间", sepia: "暖黄", blush: "粉雾" })[state.settings.theme]); }
  function addBookmark() { tool("add_reading_bookmark", { book_ref: state.book.id, page: state.page }).then(function (result) { if (result.bookmark && !state.bookmarks.some(function (item) { return Number(item.page) === Number(result.bookmark.page); })) state.bookmarks.push(result.bookmark); updateBookmarkButton(); toast(result.already_exists ? "这一页已经夹好书签了" : "书签已夹在这里"); }).catch(function (error) { toast(error.message || "书签保存失败"); }); }
  function openToc() { closeModals(); el.tocSheet.hidden = false; el.tocList.innerHTML = '<p class="toc-empty">正在整理章节…</p>'; tool("get_reading_toc", { book_ref: state.book.id, include_future: true }).then(function (result) { var entries = result.entries || []; el.tocList.innerHTML = entries.length ? entries.map(function (entry) { return '<button class="toc-item" data-toc-page="' + Number(entry.page) + '"><span>' + esc(entry.title) + '</span><small>第 ' + Number(entry.page) + ' 页</small></button>'; }).join("") : '<p class="toc-empty">没有识别到章节标题。你仍可以拖动顶部进度条跳到全书任意位置。</p>'; }).catch(function () { el.tocList.innerHTML = '<p class="toc-empty">目录读取失败，稍后再试试。</p>'; }); }
  function openAiPicker() { closeModals(); el.aiSheet.hidden = false; el.conversationList.innerHTML = '<p class="toc-empty">正在读取 Daddy 的聊天窗口…</p>'; getConversations().then(function (result) { if (!result || result.success === false) throw new Error(result && result.error || "聊天窗口读取失败"); var items = result.conversations || []; el.conversationList.innerHTML = items.length ? items.map(function (item) { var selected = item.id === state.boundConversationId; return '<button class="conversation-option ' + (selected ? "is-selected" : "") + '" data-conversation-id="' + esc(item.id) + '" data-conversation-title="' + esc(item.title) + '"><span class="conversation-avatar">D</span><span><b>' + esc(item.title || "新聊天") + '</b><small>Daddy 聊天窗口</small></span><i class="conversation-check">' + (selected ? "✓" : "") + '</i></button>'; }).join("") : '<p class="conversation-empty">还没有可以选的聊天窗口。先在 Daddy 里开始一段聊天，再回到书房选择它。</p>'; }).catch(function (error) { el.conversationList.innerHTML = '<p class="conversation-empty">' + esc(error.message || "聊天窗口读取失败") + '</p>'; }); }
  function bindConversation(button) { state.boundConversationId = button.getAttribute("data-conversation-id") || ""; state.boundConversationTitle = button.getAttribute("data-conversation-title") || "Daddy"; Promise.all([setData(BOUND_CONVERSATION_KEY, state.boundConversationId), setData(BOUND_CONVERSATION_TITLE_KEY, state.boundConversationTitle)]).then(function () { renderBinding(); closeModals(); toast("共读会交给「" + state.boundConversationTitle + "」里的 Daddy"); }).catch(function () { toast("保存聊天窗口失败"); }); }
  function captureSelection() { var selection = window.getSelection ? window.getSelection().toString() : ""; selection = text(selection); if (!selection || selection.length < 2) return false; state.selectedQuote = selection.slice(0, 1500); el.selectionPreview.textContent = "“" + state.selectedQuote.slice(0, 18) + (state.selectedQuote.length > 18 ? "…" : "") + "”"; el.selectionAction.hidden = false; return true; }
  function clearSelectionAction() { el.selectionAction.hidden = true; }
  function openNoteComposer(note) { if (!state.boundConversationId) { toast("先在书架首页选择一个 Daddy 聊天窗口吧"); openAiPicker(); return; } state.activeNote = note || null; closeModals(); el.noteSheet.hidden = false; el.noteReply.hidden = true; el.noteInput.value = note ? note.content || "" : ""; el.noteInput.disabled = !!note; el.submitNote.hidden = !!note; el.noteQuote.textContent = note ? (note.quote || "这条共读感想") : (state.selectedQuote ? "“" + state.selectedQuote + "”" : "选一句文字后再写感想"); if (note && note.ai_reply) { el.noteReply.hidden = false; el.noteReply.innerHTML = "<b>Daddy 的回应</b>" + esc(note.ai_reply); } else if (note) { el.noteReply.hidden = false; el.noteReply.innerHTML = "<b>共读状态</b>Daddy 还在这段话旁边，等会儿再来看看。"; } }
  function submitReflection() { var content = text(el.noteInput.value); if (!state.selectedQuote) { toast("先选中书里的那句话吧"); return; } if (!content) { toast("写一句感想再交给 Daddy 吧"); return; } el.submitNote.disabled = true; el.submitNote.textContent = "Daddy 正在读…"; tool("add_reading_note", { book_ref: state.book.id, page: state.page, author: "user", quote: state.selectedQuote, content: content }).then(function (result) { if (result.success === false || !result.note) throw new Error(result.error || "感想没有保存成功"); state.activeNote = result.note; el.noteReply.hidden = false; el.noteReply.innerHTML = "<b>已留在书页上</b>Daddy 正在带着「" + esc(state.boundConversationTitle || "这个聊天窗口") + "」的记忆读你的感想…"; renderCurrentRange(); var prompt = "【书房来讯】\n《" + state.book.title + "》第 " + state.page + " 页\n「" + state.selectedQuote + "」\n\n应帆的感想：\n" + content; return sendConversationMessage(state.boundConversationId, prompt); }).then(function (response) { if (!response || response.success === false) throw new Error(response && response.error || "Daddy 没有回复成功"); return tool("update_reading_note_reply", { note_id: state.activeNote.id, reply: response.reply }); }).then(function (result) { if (result.success === false) throw new Error(result.error || "回复没有写回书页"); state.activeNote = result.note; el.noteReply.hidden = false; el.noteReply.innerHTML = "<b>Daddy 的回应</b>" + esc(result.note.ai_reply); renderCurrentRange(); clearSelectionAction(); }).catch(function (error) { el.noteReply.hidden = false; el.noteReply.innerHTML = "<b>这条感想已留在书页上</b>" + esc(error.message || "Daddy 暂时没有回复成功，可以稍后重试。") + ""; }).finally(function () { el.submitNote.disabled = false; el.submitNote.textContent = "交给 Daddy"; }); }
  function renderCurrentRange() { var first = el.text.querySelector(".read-page"), last = el.text.querySelectorAll(".read-page"), from = first ? Number(first.getAttribute("data-page")) : state.page, to = last.length ? Number(last[last.length - 1].getAttribute("data-page")) : state.rangeEnd; if (!state.book) return; fetchRange(from, to).then(function (pages) { renderPages(pages, false); }); }
  function closeModals() { el.tocSheet.hidden = true; el.noteSheet.hidden = true; el.aiSheet.hidden = true; }
  function switchView(view) { if (view === "about") { toast("选一个聊天窗口，再和 Daddy 在书页旁边慢慢聊。♡"); return; } state.view = view; renderLibrary(); }
  function openBookmark(bookId, page) { var book = state.books.find(function (item) { return item.id === bookId; }); if (!book) { toast("找不到这本书了"); return; } state.view = "library"; renderLibrary(); openBook(book, page); }
  function init() {
    ["library", "bookmarkPanel", "empty", "importButton", "aiBindingButton", "aiBindingTitle", "aiBindingCopy", "reader", "readerContent", "back", "bookTitle", "pageInfo", "readingProgress", "chapterHint", "text", "loadingMore", "tocButton", "tocTool", "bookmarkButton", "fontDown", "fontUp", "themeButton", "brightnessButton", "brightnessPopover", "brightness", "dimmer", "selectionAction", "selectionPreview", "tocSheet", "tocList", "noteSheet", "noteQuote", "noteInput", "submitNote", "noteReply", "aiSheet", "conversationList", "toast"].forEach(function (name) { el[name] = id(name); });
    el.importButton.onclick = importBook; el.aiBindingButton.onclick = openAiPicker;
    el.library.onclick = function (event) { var button = event.target.closest("button[data-open]"); if (!button) return; var article = button.closest(".book"), book = article && state.books.find(function (item) { return item.id === article.getAttribute("data-id"); }); if (book) openBook(book); };
    el.bookmarkPanel.onclick = function (event) { var item = event.target.closest("button[data-bookmark-book]"); if (item) openBookmark(item.getAttribute("data-bookmark-book"), Number(item.getAttribute("data-bookmark-page"))); };
    Array.prototype.forEach.call(document.querySelectorAll(".nav-item"), function (button) { button.onclick = function () { switchView(button.getAttribute("data-view")); }; });
    el.back.onclick = function () { el.reader.hidden = true; document.body.style.overflow = ""; clearSelectionAction(); closeModals(); load(); };
    el.tocButton.onclick = openToc; el.tocTool.onclick = openToc; el.bookmarkButton.onclick = addBookmark; el.fontDown.onclick = function () { changeFont(-1); }; el.fontUp.onclick = function () { changeFont(1); }; el.themeButton.onclick = cycleTheme; el.brightnessButton.onclick = function () { el.brightnessPopover.hidden = !el.brightnessPopover.hidden; setReaderControlsVisible(true); };
    el.brightness.oninput = function () { state.settings.brightness = Number(el.brightness.value); applySettings(); savePreferences(); };
    el.readingProgress.oninput = function () { var page = Number(el.readingProgress.value); if (state.book) { state.page = page; updateReaderHeader(); } };
    el.readingProgress.onchange = function () { loadReadingWindow(Number(el.readingProgress.value), true); };
    el.reader.addEventListener("scroll", onReaderScroll, { passive: true });
    el.text.addEventListener("mouseup", function () { setTimeout(captureSelection, 0); }); el.text.addEventListener("touchend", function () { setTimeout(captureSelection, 120); }, { passive: true });
    el.text.onclick = function (event) { if (event.target.closest("button")) return; if (!captureSelection()) toggleReaderControls(); };
    el.selectionAction.onclick = function () { openNoteComposer(null); };
    el.submitNote.onclick = submitReflection;
    document.addEventListener("click", function (event) { if (!event.target.closest("#brightnessButton, #brightnessPopover")) el.brightnessPopover.hidden = true; if (event.target.matches("[data-close-modal]")) closeModals(); var toc = event.target.closest("button[data-toc-page]"); if (toc) { closeModals(); loadReadingWindow(Number(toc.getAttribute("data-toc-page")), true); } var conversation = event.target.closest("button[data-conversation-id]"); if (conversation) bindConversation(conversation); var note = event.target.closest("button[data-note-id]"); if (note) { var noteId = note.getAttribute("data-note-id"), notePage = note.closest(".read-page"); tool("read_book_page", { book_ref: state.book.id, page: notePage ? Number(notePage.getAttribute("data-page")) : state.page, allow_spoiler: true }).then(function (result) { var found = (result.notes || []).find(function (item) { return item.id === noteId; }); if (found) openNoteComposer(found); }); } });
    loadPreferences().then(load);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
