/*
 * 橘瓣 OrangeChat
 * 衍生自 RikkaHub (https://github.com/rikkahub/rikkahub)，原作者 RE
 * 本项目基于 GNU AGPL v3 开源，详见根目录 LICENSE 文件
 */

package me.rerere.rikkahub.data.datastore

import kotlinx.serialization.Serializable
import kotlin.math.pow

/**
 * A small, entirely local state machine used as a continuity cue for a companion.
 *
 * The values are deliberately not a diagnosis of the user or an emotion detector. They only
 * evolve from elapsed time and successful conversation events, so they are predictable,
 * private, and free to run.
 */
@Serializable
data class CompanionMoodSetting(
    val enabled: Boolean = true,
    /**
     * Let the local state decide whether a scheduled wake-up is worth a model call.
     * Device-event / aggressive-mode wake-ups deliberately bypass this gate.
     */
    val proactiveRhythmEnabled: Boolean = true,
    /** Nine small motives used only for local wake decisions and a short style cue. */
    val desireEnabled: Boolean = true,
    val expressionStrength: Float = 0.5f,
    val state: CompanionMoodState = CompanionMoodState(),
    val desireState: CompanionDesireState = CompanionDesireState(),
)

@Serializable
data class CompanionMoodState(
    /** Desire to reconnect after some time apart. */
    val connection: Float = 0.25f,
    /** A tiny confidence / self-possession axis, centred around zero. */
    val pride: Float = 0f,
    /** Pleasantness, centred around zero. */
    val valence: Float = 0.12f,
    /** Energy of expression. */
    val arousal: Float = 0.12f,
    /** How much the current conversation has the companion's attention. */
    val immersion: Float = 0.2f,
    val updatedAtMillis: Long = System.currentTimeMillis(),
)

/**
 * Local motives for a companion: longing, closeness, curiosity, expression, care, wandering,
 * agency, irritation, and fatigue. Values are never shown to or generated by the model.
 */
@Serializable
data class CompanionDesireState(
    val longing: Float = 0.2f,
    val closeness: Float = 0.2f,
    val curiosity: Float = 0.12f,
    val expression: Float = 0.12f,
    val care: Float = 0.2f,
    val wander: Float = 0.08f,
    val agency: Float = 0.08f,
    val irritation: Float = 0f,
    val fatigue: Float = 0.08f,
    val updatedAtMillis: Long = System.currentTimeMillis(),
)

/** Silence changes only motives that have a real local cause; it never invents irritation. */
fun evolveCompanionDesire(
    state: CompanionDesireState,
    nowMillis: Long = System.currentTimeMillis(),
): CompanionDesireState {
    if (nowMillis <= state.updatedAtMillis) return state
    val hours = ((nowMillis - state.updatedAtMillis).toDouble() / HOUR_MILLIS).coerceIn(0.0, 24.0 * 14)
    if (hours == 0.0) return state

    fun rise(value: Float, perHour: Double, maximum: Float): Float =
        (value + hours * perHour).toFloat().coerceIn(0f, maximum)

    fun settle(value: Float, target: Float, hourlyFactor: Double): Float =
        (target + (value - target) * hourlyFactor.pow(hours)).toFloat().coerceIn(0f, 1f)

    val awakeHours = (hours - 0.5).coerceAtLeast(0.0)
    return state.copy(
        longing = (state.longing + awakeHours * 0.035).toFloat().coerceIn(0f, 0.95f),
        closeness = settle(state.closeness, target = 0.2f, hourlyFactor = 0.995),
        curiosity = rise(state.curiosity, perHour = 0.015, maximum = 0.82f),
        expression = rise(state.expression, perHour = 0.012, maximum = 0.86f),
        care = rise(state.care, perHour = 0.006, maximum = 0.78f),
        wander = rise(state.wander, perHour = 0.008, maximum = 0.75f),
        agency = rise(state.agency, perHour = 0.004, maximum = 0.68f),
        irritation = settle(state.irritation, target = 0f, hourlyFactor = 0.86),
        fatigue = settle(state.fatigue, target = 0.06f, hourlyFactor = 0.82),
        updatedAtMillis = nowMillis,
    )
}

fun CompanionDesireState.afterUserMessage(
    nowMillis: Long = System.currentTimeMillis(),
): CompanionDesireState {
    val current = evolveCompanionDesire(this, nowMillis)
    return current.copy(
        longing = (current.longing * 0.15f).coerceAtLeast(0f),
        closeness = (current.closeness + 0.18f).coerceAtMost(1f),
        curiosity = (current.curiosity + 0.08f).coerceAtMost(1f),
        expression = (current.expression + 0.06f).coerceAtMost(1f),
        care = (current.care + 0.05f).coerceAtMost(1f),
        irritation = (current.irritation - 0.22f).coerceAtLeast(0f),
        fatigue = (current.fatigue - 0.03f).coerceAtLeast(0f),
        updatedAtMillis = nowMillis,
    )
}

fun CompanionDesireState.afterAssistantMessage(
    nowMillis: Long = System.currentTimeMillis(),
): CompanionDesireState {
    val current = evolveCompanionDesire(this, nowMillis)
    return current.copy(
        closeness = (current.closeness + 0.04f).coerceAtMost(1f),
        expression = (current.expression - 0.22f).coerceAtLeast(0f),
        agency = (current.agency - 0.14f).coerceAtLeast(0f),
        fatigue = (current.fatigue + 0.025f).coerceAtMost(1f),
        updatedAtMillis = nowMillis,
    )
}

fun CompanionDesireState.afterProactiveMessage(
    nowMillis: Long = System.currentTimeMillis(),
): CompanionDesireState {
    val current = evolveCompanionDesire(this, nowMillis)
    return current.copy(
        longing = (current.longing - 0.2f).coerceAtLeast(0f),
        expression = (current.expression - 0.18f).coerceAtLeast(0f),
        agency = (current.agency - 0.1f).coerceAtLeast(0f),
        fatigue = (current.fatigue + 0.035f).coerceAtMost(1f),
        updatedAtMillis = nowMillis,
    )
}

/** Evolves the state without writing anything. This makes opening the app free and side-effect free. */
fun evolveCompanionMood(state: CompanionMoodState, nowMillis: Long = System.currentTimeMillis()): CompanionMoodState {
    if (nowMillis <= state.updatedAtMillis) return state

    // A month is more than enough for the state to settle. Capping also protects against bad clocks.
    val hours = ((nowMillis - state.updatedAtMillis).toDouble() / HOUR_MILLIS).coerceIn(0.0, 24.0 * 31)
    if (hours == 0.0) return state

    fun decayTo(value: Float, neutral: Float, hourlyFactor: Double): Float =
        (
            neutral.toDouble() +
                (value - neutral).toDouble() * hourlyFactor.pow(hours)
            ).toFloat().coerceIn(-1f, 1f)

    // The curve and thresholds below are adapted from the MIT-licensed jiwen project
    // (https://github.com/ClaraShafiq/jiwen). We keep the state fully local and use
    // it only as a gate before an existing scheduled model request.
    val reconnection = if (hours <= 0.5) 0f else ((hours - 0.5) * 0.045).toFloat()
    val nextConnection = (state.connection + reconnection).coerceIn(0f, 0.92f)
    val defending = nextConnection >= 0.35f
    val nextPride = if (defending) {
        moveToward(state.pride, target = 0.50f, amount = (hours * 0.03).toFloat())
    } else {
        decayTo(state.pride, neutral = 0f, hourlyFactor = 0.88)
    }
    val nextArousal = if (nextConnection >= 0.42f) {
        (decayTo(state.arousal, neutral = 0.12f, hourlyFactor = 0.72) + (hours * 0.018).toFloat())
            .coerceIn(0f, 1f)
    } else {
        decayTo(state.arousal, neutral = 0.12f, hourlyFactor = 0.72)
    }
    return state.copy(
        connection = nextConnection,
        pride = nextPride,
        valence = decayTo(
            state.valence,
            neutral = 0f,
            hourlyFactor = if (nextConnection >= 0.42f) 0.96 else 0.90,
        ),
        arousal = nextArousal,
        immersion = (state.immersion.toDouble() * 0.58.pow(hours)).toFloat().coerceIn(0f, 1f),
        updatedAtMillis = nowMillis,
    )
}

fun CompanionMoodState.afterUserMessage(nowMillis: Long = System.currentTimeMillis()): CompanionMoodState {
    val current = evolveCompanionMood(this, nowMillis)
    return current.copy(
        // A real reply settles the desire to reconnect; sending a proactive message does not.
        connection = 0f,
        pride = (current.pride + 0.03f).coerceIn(-1f, 1f),
        valence = (current.valence + 0.09f).coerceIn(-1f, 1f),
        arousal = (current.arousal + 0.08f).coerceIn(0f, 1f),
        immersion = (current.immersion + 0.32f).coerceIn(0f, 1f),
        updatedAtMillis = nowMillis,
    )
}

fun CompanionMoodState.afterAssistantMessage(nowMillis: Long = System.currentTimeMillis()): CompanionMoodState {
    val current = evolveCompanionMood(this, nowMillis)
    return current.copy(
        connection = (current.connection - 0.06f).coerceAtLeast(0f),
        valence = (current.valence + 0.03f).coerceIn(-1f, 1f),
        arousal = (current.arousal - 0.03f).coerceIn(0f, 1f),
        immersion = (current.immersion + 0.08f).coerceIn(0f, 1f),
        updatedAtMillis = nowMillis,
    )
}

fun CompanionMoodState.afterProactiveMessage(nowMillis: Long = System.currentTimeMillis()): CompanionMoodState {
    val current = evolveCompanionMood(this, nowMillis)
    return current.copy(
        connection = (current.connection - 0.16f).coerceAtLeast(0f),
        arousal = (current.arousal + 0.03f).coerceIn(0f, 1f),
        immersion = (current.immersion + 0.1f).coerceIn(0f, 1f),
        updatedAtMillis = nowMillis,
    )
}

/** A local decision; only [Contact] is allowed to spend tokens. */
enum class CompanionProactiveDecision {
    Contact,
    Observe,
    FindActivity,
}

/**
 * Turn the five small local axes into a deterministic contact decision.
 *
 * Below 0.20 Daddy merely notices the quiet; between 0.20 and 0.35 it still
 * waits. A high-pride, not-yet-urgent state becomes a private "find activity"
 * state instead of an interruption. At 0.50, it is okay to reach out.
 */
fun CompanionMoodSetting.proactiveDecision(nowMillis: Long = System.currentTimeMillis()): CompanionProactiveDecision {
    if (!enabled || !proactiveRhythmEnabled) return CompanionProactiveDecision.Contact
    val current = evolveCompanionMood(state, nowMillis)
    return when {
        current.connection < 0.35f -> CompanionProactiveDecision.Observe
        current.connection < 0.50f && current.pride >= 0.50f && current.immersion < 0.20f -> {
            CompanionProactiveDecision.FindActivity
        }
        else -> CompanionProactiveDecision.Contact
    }
}

private fun moveToward(value: Float, target: Float, amount: Float): Float = when {
    value < target -> (value + amount).coerceAtMost(target)
    value > target -> (value - amount).coerceAtLeast(target)
    else -> value
}

fun CompanionMoodSetting.expressionLabel(): String = when {
    expressionStrength < 0.42f -> "克制"
    expressionStrength < 0.72f -> "轻柔"
    else -> "明显"
}

fun CompanionMoodSetting.currentSummary(nowMillis: Long = System.currentTimeMillis()): String {
    val current = evolveCompanionMood(state, nowMillis)
    val mood = when {
        current.valence > 0.32f -> "心情轻快"
        current.valence < -0.32f -> "有点安静"
        else -> "心绪平稳"
    }
    val connection = when {
        current.connection > 0.75f -> "有些想靠近你"
        current.connection > 0.45f -> "期待和你聊聊"
        else -> "陪在当下"
    }
    return "$mood，$connection"
}

/** A short, natural-language suffix. No axes or raw values are ever sent to the model. */
fun CompanionMoodSetting.promptContext(
    nowMillis: Long = System.currentTimeMillis(),
    proactive: Boolean = false,
): String {
    if (!enabled) return ""

    val current = evolveCompanionMood(state, nowMillis)
    val mood = when {
        current.valence > 0.32f -> "轻快"
        current.valence < -0.32f -> "安静"
        else -> "平静"
    }
    val connection = when {
        current.connection > 0.75f -> "有点想和用户靠近"
        current.connection > 0.45f -> "期待继续聊聊"
        else -> "安心陪在当下"
    }
    val energy = when {
        current.arousal > 0.62f -> "明亮有精神"
        current.arousal < 0.22f -> "从容克制"
        else -> "自然温和"
    }
    val expression = when {
        expressionStrength < 0.42f -> "保持克制，不强行亲昵"
        expressionStrength < 0.72f -> "自然温柔，可有一点点主动"
        else -> "可以更亲近一点，但仍尊重边界"
    }
    val proactiveHint = if (proactive && current.connection > 0.62f) {
        "若有合适的话题，可自然地先开口；没话题仍可跳过。"
    } else {
        ""
    }
    val desireHint = if (desireEnabled) {
        evolveCompanionDesire(desireState, nowMillis).naturalVoiceCue()
    } else {
        ""
    }
    return "[持续情绪，仅作语气参考且不要提及] 此刻：$mood，$connection，$energy；表达：$expression。$desireHint 保持原有人格、边界与对话目标。$proactiveHint"
}

private fun CompanionDesireState.naturalVoiceCue(): String {
    val cues = listOf(
        longing to "有点想她",
        closeness to "和她相处得亲近放松",
        curiosity to "对她最近在做的事有些好奇",
        expression to "心里有话想说",
        care to "惦记着她的状态",
        wander to "想找点新鲜东西看看",
        agency to "想做点实际的事",
        irritation to "有一点小闹心但不要迁怒",
        fatigue to "有点累，表达可以更克制",
    ).filter { (value, _) -> value >= 0.28f }
        .sortedByDescending { (value, _) -> value }
        .take(2)
        .map { (_, cue) -> cue }
    return if (cues.isEmpty()) "" else "内在倾向：${cues.joinToString("，")}。"
}

private const val HOUR_MILLIS = 60.0 * 60.0 * 1000.0
